#pragma once

// Generated by tools/generate_thz55eco_esphome_points.py.
// Source: docs/reference/thz55eco_observed_bulk_points.json

namespace esphome {
namespace thz55eco {

static constexpr uint8_t REQUEST_fb[] = {0xFB};
static constexpr uint8_t REQUEST_f2[] = {0xF2};
static constexpr uint8_t REQUEST_f4[] = {0xF4};
static constexpr uint8_t REQUEST_f3[] = {0xF3};
static constexpr uint8_t REQUEST_f5[] = {0xF5};
static constexpr uint8_t REQUEST_fc[] = {0xFC};
static constexpr uint8_t REQUEST_16[] = {0x16};
static constexpr uint8_t REQUEST_e8[] = {0xE8};
static constexpr uint8_t REQUEST_09[] = {0x09};
static constexpr uint8_t REQUEST_d1[] = {0xD1};
static constexpr uint8_t REQUEST_0a091a[] = {0x0A, 0x09, 0x1A};
static constexpr uint8_t REQUEST_0a091b[] = {0x0A, 0x09, 0x1B};
static constexpr uint8_t REQUEST_0a091c[] = {0x0A, 0x09, 0x1C};
static constexpr uint8_t REQUEST_0a091d[] = {0x0A, 0x09, 0x1D};
static constexpr uint8_t REQUEST_0a091e[] = {0x0A, 0x09, 0x1E};
static constexpr uint8_t REQUEST_0a091f[] = {0x0A, 0x09, 0x1F};
static constexpr uint8_t REQUEST_0a0920[] = {0x0A, 0x09, 0x20};
static constexpr uint8_t REQUEST_0a0921[] = {0x0A, 0x09, 0x21};
static constexpr uint8_t REQUEST_0a092a[] = {0x0A, 0x09, 0x2A};
static constexpr uint8_t REQUEST_0a092b[] = {0x0A, 0x09, 0x2B};
static constexpr uint8_t REQUEST_0a092c[] = {0x0A, 0x09, 0x2C};
static constexpr uint8_t REQUEST_0a092d[] = {0x0A, 0x09, 0x2D};
static constexpr uint8_t REQUEST_0a092e[] = {0x0A, 0x09, 0x2E};
static constexpr uint8_t REQUEST_0a092f[] = {0x0A, 0x09, 0x2F};
static constexpr uint8_t REQUEST_0a0930[] = {0x0A, 0x09, 0x30};
static constexpr uint8_t REQUEST_0a0931[] = {0x0A, 0x09, 0x31};
static constexpr uint8_t REQUEST_0a03ae[] = {0x0A, 0x03, 0xAE};
static constexpr uint8_t REQUEST_0a03af[] = {0x0A, 0x03, 0xAF};
static constexpr uint8_t REQUEST_0a03b0[] = {0x0A, 0x03, 0xB0};
static constexpr uint8_t REQUEST_0a03b1[] = {0x0A, 0x03, 0xB1};
static constexpr uint8_t REQUEST_0a069a[] = {0x0A, 0x06, 0x9A};

static constexpr BulkRequestDefinition THZ55ECO_BULK_REQUESTS[] = {
    {REQUEST_fb, sizeof(REQUEST_fb), "global"},
    {REQUEST_f2, sizeof(REQUEST_f2), "control"},
    {REQUEST_f4, sizeof(REQUEST_f4), "heating_circuit_1"},
    {REQUEST_f3, sizeof(REQUEST_f3), "domestic_hot_water"},
    {REQUEST_f5, sizeof(REQUEST_f5), "heating_circuit_2"},
    {REQUEST_fc, sizeof(REQUEST_fc), "time_date"},
    {REQUEST_16, sizeof(REQUEST_16), "solar"},
    {REQUEST_e8, sizeof(REQUEST_e8), "fan"},
    {REQUEST_09, sizeof(REQUEST_09), "history"},
    {REQUEST_d1, sizeof(REQUEST_d1), "last_errors"},
    {REQUEST_0a091a, sizeof(REQUEST_0a091a), "electrical_dhw_day_low_part"},
    {REQUEST_0a091b, sizeof(REQUEST_0a091b), "electrical_dhw_day_high_part"},
    {REQUEST_0a091c, sizeof(REQUEST_0a091c), "electrical_dhw_total_low_part"},
    {REQUEST_0a091d, sizeof(REQUEST_0a091d), "electrical_dhw_total_high_part"},
    {REQUEST_0a091e, sizeof(REQUEST_0a091e), "electrical_heating_circuit_day_low_part"},
    {REQUEST_0a091f, sizeof(REQUEST_0a091f), "electrical_heating_circuit_day_high_part"},
    {REQUEST_0a0920, sizeof(REQUEST_0a0920), "electrical_heating_circuit_total_low_part"},
    {REQUEST_0a0921, sizeof(REQUEST_0a0921), "electrical_heating_circuit_total_high_part"},
    {REQUEST_0a092a, sizeof(REQUEST_0a092a), "heat_dhw_day_low_part"},
    {REQUEST_0a092b, sizeof(REQUEST_0a092b), "heat_dhw_day_high_part"},
    {REQUEST_0a092c, sizeof(REQUEST_0a092c), "heat_dhw_total_low_part"},
    {REQUEST_0a092d, sizeof(REQUEST_0a092d), "heat_dhw_total_high_part"},
    {REQUEST_0a092e, sizeof(REQUEST_0a092e), "heat_heating_circuit_day_low_part"},
    {REQUEST_0a092f, sizeof(REQUEST_0a092f), "heat_heating_circuit_day_high_part"},
    {REQUEST_0a0930, sizeof(REQUEST_0a0930), "heat_heating_circuit_total_low_part"},
    {REQUEST_0a0931, sizeof(REQUEST_0a0931), "heat_heating_circuit_total_high_part"},
    {REQUEST_0a03ae, sizeof(REQUEST_0a03ae), "heat_recovered_day_low_part"},
    {REQUEST_0a03af, sizeof(REQUEST_0a03af), "heat_recovered_day_high_part"},
    {REQUEST_0a03b0, sizeof(REQUEST_0a03b0), "heat_recovered_total_low_part"},
    {REQUEST_0a03b1, sizeof(REQUEST_0a03b1), "heat_recovered_total_high_part"},
    {REQUEST_0a069a, sizeof(REQUEST_0a069a), "heating_relative_power"},
};

static constexpr PointDefinition THZ55ECO_POINTS[] = {
    {"history_compressor_heating", REQUEST_09, sizeof(REQUEST_09), 4, 2, 1.0f, -1},
    {"history_compressor_cooling", REQUEST_09, sizeof(REQUEST_09), 6, 2, 1.0f, -1},
    {"history_compressor_domestic_hot_water", REQUEST_09, sizeof(REQUEST_09), 8, 2, 1.0f, -1},
    {"history_booster_domestic_hot_water", REQUEST_09, sizeof(REQUEST_09), 10, 2, 1.0f, -1},
    {"history_booster_heating", REQUEST_09, sizeof(REQUEST_09), 12, 2, 1.0f, -1},
    {"solar_collector_temp", REQUEST_16, sizeof(REQUEST_16), 4, 2, 0.1f, -1},
    {"solar_domestic_hot_water_temp", REQUEST_16, sizeof(REQUEST_16), 6, 2, 0.1f, -1},
    {"solar_flow_temp", REQUEST_16, sizeof(REQUEST_16), 8, 2, 0.1f, -1},
    {"solar_pump_duty", REQUEST_16, sizeof(REQUEST_16), 10, 1, 1.0f, -1},
    {"solar_output_state", REQUEST_16, sizeof(REQUEST_16), 15, 2, 1.0f, -1},
    {"solar_status", REQUEST_16, sizeof(REQUEST_16), 17, 1, 1.0f, -1},
    {"last_errors_number_of_faults", REQUEST_d1, sizeof(REQUEST_d1), 4, 1, 1.0f, -1},
    {"last_errors_fault0_code", REQUEST_d1, sizeof(REQUEST_d1), 6, 1, 1.0f, -1},
    {"last_errors_fault1_code", REQUEST_d1, sizeof(REQUEST_d1), 12, 1, 1.0f, -1},
    {"last_errors_fault2_code", REQUEST_d1, sizeof(REQUEST_d1), 18, 1, 1.0f, -1},
    {"last_errors_fault3_code", REQUEST_d1, sizeof(REQUEST_d1), 24, 1, 1.0f, -1},
    {"fan_input_fan_speed", REQUEST_e8, sizeof(REQUEST_e8), 31, 1, 1.0f, -1},
    {"fan_output_fan_speed", REQUEST_e8, sizeof(REQUEST_e8), 32, 1, 1.0f, -1},
    {"fan_stage_airflow_inlet", REQUEST_e8, sizeof(REQUEST_e8), 33, 2, 1.0f, -1},
    {"fan_stage_airflow_outlet", REQUEST_e8, sizeof(REQUEST_e8), 35, 2, 1.0f, -1},
    {"fan_input_fan_power", REQUEST_e8, sizeof(REQUEST_e8), 37, 1, 1.0f, -1},
    {"fan_output_fan_power", REQUEST_e8, sizeof(REQUEST_e8), 38, 1, 1.0f, -1},
    {"control_heat_request", REQUEST_f2, sizeof(REQUEST_f2), 4, 1, 1.0f, -1},
    {"control_heat_request2", REQUEST_f2, sizeof(REQUEST_f2), 5, 1, 1.0f, -1},
    {"control_heating_circuit_stage", REQUEST_f2, sizeof(REQUEST_f2), 6, 1, 1.0f, -1},
    {"control_domestic_hot_water_stage", REQUEST_f2, sizeof(REQUEST_f2), 7, 1, 1.0f, -1},
    {"control_heat_stage_control_modul", REQUEST_f2, sizeof(REQUEST_f2), 8, 1, 1.0f, -1},
    {"control_comp_block_time", REQUEST_f2, sizeof(REQUEST_f2), 9, 2, 1.0f, -1},
    {"control_pasteurisation_mode", REQUEST_f2, sizeof(REQUEST_f2), 11, 1, 1.0f, -1},
    {"control_defrost_evaporator", REQUEST_f2, sizeof(REQUEST_f2), 12, 1, 1.0f, -1},
    {"control_booster_stage2", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, -1},
    {"control_solar_pump", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 1},
    {"control_booster_stage1", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 2},
    {"control_compressor", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 3},
    {"control_heat_pipe_valve", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 4},
    {"control_diverter_valve", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 5},
    {"control_domestic_hot_water_pump", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 6},
    {"control_heating_circuit_pump", REQUEST_f2, sizeof(REQUEST_f2), 13, 1, 1.0f, 7},
    {"control_mixer_open", REQUEST_f2, sizeof(REQUEST_f2), 14, 1, 1.0f, 6},
    {"control_mixer_closed", REQUEST_f2, sizeof(REQUEST_f2), 14, 1, 1.0f, 7},
    {"control_sensor_bits1", REQUEST_f2, sizeof(REQUEST_f2), 15, 1, 1.0f, -1},
    {"control_sensor_bits2", REQUEST_f2, sizeof(REQUEST_f2), 16, 1, 1.0f, -1},
    {"control_boost_block_time_after_pump_start", REQUEST_f2, sizeof(REQUEST_f2), 17, 2, 1.0f, -1},
    {"control_boost_block_time_after_high_pressure", REQUEST_f2, sizeof(REQUEST_f2), 19, 2, 1.0f, -1},
    {"domestic_hot_water_temp", REQUEST_f3, sizeof(REQUEST_f3), 4, 2, 0.1f, -1},
    {"domestic_hot_water_outside_temp", REQUEST_f3, sizeof(REQUEST_f3), 6, 2, 0.1f, -1},
    {"domestic_hot_water_set_temp", REQUEST_f3, sizeof(REQUEST_f3), 8, 2, 0.1f, -1},
    {"domestic_hot_water_comp_block_time", REQUEST_f3, sizeof(REQUEST_f3), 10, 2, 1.0f, -1},
    {"domestic_hot_water_output_state", REQUEST_f3, sizeof(REQUEST_f3), 12, 2, 1.0f, -1},
    {"domestic_hot_water_heat_block_time", REQUEST_f3, sizeof(REQUEST_f3), 14, 2, 1.0f, -1},
    {"domestic_hot_water_booster_stage", REQUEST_f3, sizeof(REQUEST_f3), 16, 1, 1.0f, -1},
    {"domestic_hot_water_pasteurisation_mode", REQUEST_f3, sizeof(REQUEST_f3), 18, 1, 1.0f, -1},
    {"domestic_hot_water_op_mode", REQUEST_f3, sizeof(REQUEST_f3), 19, 1, 1.0f, -1},
    {"domestic_hot_water_unknown_x36", REQUEST_f3, sizeof(REQUEST_f3), 20, 2, 1.0f, -1},
    {"heating_circuit_1_outside_temp", REQUEST_f4, sizeof(REQUEST_f4), 4, 2, 0.1f, -1},
    {"heating_circuit_1_unknown_x08", REQUEST_f4, sizeof(REQUEST_f4), 6, 2, 0.1f, -1},
    {"heating_circuit_1_return_temp", REQUEST_f4, sizeof(REQUEST_f4), 8, 2, 0.1f, -1},
    {"heating_circuit_1_integral_heat", REQUEST_f4, sizeof(REQUEST_f4), 10, 2, 1.0f, -1},
    {"heating_circuit_1_flow_temp", REQUEST_f4, sizeof(REQUEST_f4), 12, 2, 0.1f, -1},
    {"heating_circuit_1_heat_set_temp", REQUEST_f4, sizeof(REQUEST_f4), 14, 2, 0.1f, -1},
    {"heating_circuit_1_heat_temp", REQUEST_f4, sizeof(REQUEST_f4), 16, 2, 0.1f, -1},
    {"heating_circuit_1_season_mode", REQUEST_f4, sizeof(REQUEST_f4), 21, 1, 1.0f, -1},
    {"heating_circuit_1_integral_switch", REQUEST_f4, sizeof(REQUEST_f4), 24, 2, 1.0f, -1},
    {"heating_circuit_1_heating_circuit_op_mode", REQUEST_f4, sizeof(REQUEST_f4), 26, 1, 1.0f, -1},
    {"heating_circuit_1_room_set_temp", REQUEST_f4, sizeof(REQUEST_f4), 30, 2, 0.1f, -1},
    {"heating_circuit_1_unknown_x60", REQUEST_f4, sizeof(REQUEST_f4), 32, 2, 0.1f, -1},
    {"heating_circuit_1_unknown_x64", REQUEST_f4, sizeof(REQUEST_f4), 34, 2, 0.1f, -1},
    {"heating_circuit_1_inside_temp_remote_control", REQUEST_f4, sizeof(REQUEST_f4), 36, 2, 0.1f, -1},
    {"heating_circuit_1_unknown_x72", REQUEST_f4, sizeof(REQUEST_f4), 38, 2, 0.1f, -1},
    {"heating_circuit_1_unknown_x76", REQUEST_f4, sizeof(REQUEST_f4), 40, 2, 0.1f, -1},
    {"heating_circuit_1_on_hysteresis_no", REQUEST_f4, sizeof(REQUEST_f4), 18, 1, 1.0f, -1},
    {"heating_circuit_1_off_hysteresis_no", REQUEST_f4, sizeof(REQUEST_f4), 19, 1, 1.0f, -1},
    {"heating_circuit_1_heating_circuit_booster_stage", REQUEST_f4, sizeof(REQUEST_f4), 20, 1, 1.0f, -1},
    {"heating_circuit_2_outside_temp", REQUEST_f5, sizeof(REQUEST_f5), 4, 2, 0.1f, -1},
    {"heating_circuit_2_return_temp", REQUEST_f5, sizeof(REQUEST_f5), 6, 2, 0.1f, -1},
    {"heating_circuit_2_flow_temp", REQUEST_f5, sizeof(REQUEST_f5), 8, 2, 0.1f, -1},
    {"heating_circuit_2_heat_set_temp", REQUEST_f5, sizeof(REQUEST_f5), 10, 2, 0.1f, -1},
    {"heating_circuit_2_heat_temp", REQUEST_f5, sizeof(REQUEST_f5), 12, 2, 0.1f, -1},
    {"heating_circuit_2_actuator_position", REQUEST_f5, sizeof(REQUEST_f5), 14, 2, 0.1f, -1},
    {"heating_circuit_2_season_mode", REQUEST_f5, sizeof(REQUEST_f5), 17, 1, 1.0f, -1},
    {"heating_circuit_2_heating_circuit_op_mode", REQUEST_f5, sizeof(REQUEST_f5), 20, 1, 1.0f, -1},
    {"global_outside_temp", REQUEST_fb, sizeof(REQUEST_fb), 6, 2, 0.1f, -1},
    {"global_flow_temp", REQUEST_fb, sizeof(REQUEST_fb), 8, 2, 0.1f, -1},
    {"global_return_temp", REQUEST_fb, sizeof(REQUEST_fb), 10, 2, 0.1f, -1},
    {"global_hot_gas_temp", REQUEST_fb, sizeof(REQUEST_fb), 12, 2, 0.1f, -1},
    {"global_domestic_hot_water_temp", REQUEST_fb, sizeof(REQUEST_fb), 14, 2, 0.1f, -1},
    {"global_flow_temp_heating_circuit2", REQUEST_fb, sizeof(REQUEST_fb), 16, 2, 0.1f, -1},
    {"global_evaporator_temp", REQUEST_fb, sizeof(REQUEST_fb), 20, 2, 0.1f, -1},
    {"global_condenser_temp", REQUEST_fb, sizeof(REQUEST_fb), 22, 2, 0.1f, -1},
    {"global_mixer_open", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, 7},
    {"global_mixer_closed", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, 6},
    {"global_heat_pipe_valve", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, 5},
    {"global_diverter_valve", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, 4},
    {"global_domestic_hot_water_pump", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, 3},
    {"global_heating_circuit_pump", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, 2},
    {"global_solar_pump", REQUEST_fb, sizeof(REQUEST_fb), 24, 1, 1.0f, -1},
    {"global_compressor", REQUEST_fb, sizeof(REQUEST_fb), 25, 1, 1.0f, 4},
    {"global_booster_stage3", REQUEST_fb, sizeof(REQUEST_fb), 25, 1, 1.0f, 3},
    {"global_booster_stage2", REQUEST_fb, sizeof(REQUEST_fb), 25, 1, 1.0f, 2},
    {"global_booster_stage1", REQUEST_fb, sizeof(REQUEST_fb), 25, 1, 1.0f, 1},
    {"global_high_pressure_sensor_inverted", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 7},
    {"global_low_pressure_sensor_inverted", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 6},
    {"global_evaporator_ice_monitor", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 5},
    {"global_signal_anode", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 4},
    {"global_utility_release", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 3},
    {"global_oven_fireplace", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 2},
    {"global_safety_temperature_limiter", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, 1},
    {"global_output_ventilator_power", REQUEST_fb, sizeof(REQUEST_fb), 27, 2, 0.1f, -1},
    {"global_input_ventilator_power", REQUEST_fb, sizeof(REQUEST_fb), 29, 2, 0.1f, -1},
    {"global_main_ventilator_power", REQUEST_fb, sizeof(REQUEST_fb), 31, 2, 0.1f, -1},
    {"global_output_ventilator_speed", REQUEST_fb, sizeof(REQUEST_fb), 33, 2, 1.0f, -1},
    {"global_input_ventilator_speed", REQUEST_fb, sizeof(REQUEST_fb), 35, 2, 1.0f, -1},
    {"global_main_ventilator_speed", REQUEST_fb, sizeof(REQUEST_fb), 37, 2, 1.0f, -1},
    {"global_outside_temp_filtered", REQUEST_fb, sizeof(REQUEST_fb), 39, 2, 0.1f, -1},
    {"global_rel_humidity", REQUEST_fb, sizeof(REQUEST_fb), 41, 2, 0.1f, -1},
    {"global_dew_point", REQUEST_fb, sizeof(REQUEST_fb), 43, 2, 0.1f, -1},
    {"global_pressure_low_side", REQUEST_fb, sizeof(REQUEST_fb), 45, 2, 0.01f, -1},
    {"global_pressure_high_side", REQUEST_fb, sizeof(REQUEST_fb), 47, 2, 0.01f, -1},
    {"global_collector_temp", REQUEST_fb, sizeof(REQUEST_fb), 4, 2, 0.1f, -1},
    {"global_inside_temp", REQUEST_fb, sizeof(REQUEST_fb), 18, 2, 0.1f, -1},
    {"global_window_open", REQUEST_fb, sizeof(REQUEST_fb), 25, 1, 1.0f, 5},
    {"global_quick_air_vent", REQUEST_fb, sizeof(REQUEST_fb), 26, 1, 1.0f, -1},
    {"global_flow_rate", REQUEST_fb, sizeof(REQUEST_fb), 57, 2, 0.01f, -1},
    {"time_date_weekday", REQUEST_fc, sizeof(REQUEST_fc), 4, 1, 1.0f, -1},
    {"time_date_hour", REQUEST_fc, sizeof(REQUEST_fc), 5, 1, 1.0f, -1},
    {"time_date_min", REQUEST_fc, sizeof(REQUEST_fc), 6, 1, 1.0f, -1},
    {"time_date_sec", REQUEST_fc, sizeof(REQUEST_fc), 7, 1, 1.0f, -1},
    {"time_date_year", REQUEST_fc, sizeof(REQUEST_fc), 8, 1, 1.0f, -1},
    {"time_date_month", REQUEST_fc, sizeof(REQUEST_fc), 9, 1, 1.0f, -1},
    {"time_date_day", REQUEST_fc, sizeof(REQUEST_fc), 10, 1, 1.0f, -1},
    {"electrical_domestic_hot_water_day_low_part", REQUEST_0a091a, sizeof(REQUEST_0a091a), 6, 2, 1.0f, -1},
    {"electrical_domestic_hot_water_total_low_part", REQUEST_0a091c, sizeof(REQUEST_0a091c), 6, 2, 1.0f, -1},
    {"electrical_heating_circuit_day_low_part", REQUEST_0a091e, sizeof(REQUEST_0a091e), 6, 2, 1.0f, -1},
    {"electrical_heating_circuit_total_low_part", REQUEST_0a0920, sizeof(REQUEST_0a0920), 6, 2, 1.0f, -1},
    {"heat_domestic_hot_water_day_low_part", REQUEST_0a092a, sizeof(REQUEST_0a092a), 6, 2, 1.0f, -1},
    {"heat_domestic_hot_water_total_low_part", REQUEST_0a092c, sizeof(REQUEST_0a092c), 6, 2, 1.0f, -1},
    {"heat_heating_circuit_day_low_part", REQUEST_0a092e, sizeof(REQUEST_0a092e), 6, 2, 1.0f, -1},
    {"heat_heating_circuit_total_low_part", REQUEST_0a0930, sizeof(REQUEST_0a0930), 6, 2, 1.0f, -1},
    {"heat_recovered_day_low_part", REQUEST_0a03ae, sizeof(REQUEST_0a03ae), 6, 2, 1.0f, -1},
    {"heat_recovered_total_low_part", REQUEST_0a03b0, sizeof(REQUEST_0a03b0), 6, 2, 1.0f, -1},
    {"heat_domestic_hot_water_day_high_part", REQUEST_0a092b, sizeof(REQUEST_0a092b), 6, 2, 1.0f, -1},
    {"heat_domestic_hot_water_total_high_part", REQUEST_0a092d, sizeof(REQUEST_0a092d), 6, 2, 1.0f, -1},
    {"heat_heating_circuit_day_high_part", REQUEST_0a092f, sizeof(REQUEST_0a092f), 6, 2, 1.0f, -1},
    {"heat_heating_circuit_total_high_part", REQUEST_0a0931, sizeof(REQUEST_0a0931), 6, 2, 1.0f, -1},
    {"heat_recovered_day_high_part", REQUEST_0a03af, sizeof(REQUEST_0a03af), 6, 2, 1.0f, -1},
    {"heat_recovered_total_high_part", REQUEST_0a03b1, sizeof(REQUEST_0a03b1), 6, 2, 1.0f, -1},
    {"heating_relative_power", REQUEST_0a069a, sizeof(REQUEST_0a069a), 6, 2, 1.0f, -1},
    {"electrical_domestic_hot_water_day_high_part", REQUEST_0a091b, sizeof(REQUEST_0a091b), 6, 2, 1.0f, -1},
    {"electrical_domestic_hot_water_total_high_part", REQUEST_0a091d, sizeof(REQUEST_0a091d), 6, 2, 1.0f, -1},
    {"electrical_heating_circuit_day_high_part", REQUEST_0a091f, sizeof(REQUEST_0a091f), 6, 2, 1.0f, -1},
    {"electrical_heating_circuit_total_high_part", REQUEST_0a0921, sizeof(REQUEST_0a0921), 6, 2, 1.0f, -1},
};

}  // namespace thz55eco
}  // namespace esphome
