"""Generate ESPHome THZ 5.5 Eco point definitions from the observed JSON mapping."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_POINTS_JSON = Path("docs/reference/thz55eco_observed_bulk_points.json")
DEFAULT_OUTPUT = Path("components/thz55eco/thz55eco_points.h")
REQUEST_ORDER = (
    "FB",
    "F2",
    "F4",
    "F3",
    "F5",
    "FC",
    "16",
    "E8",
    "09",
    "D1",
    "0A091A",
    "0A091B",
    "0A091C",
    "0A091D",
    "0A091E",
    "0A091F",
    "0A0920",
    "0A0921",
    "0A092A",
    "0A092B",
    "0A092C",
    "0A092D",
    "0A092E",
    "0A092F",
    "0A0930",
    "0A0931",
    "0A03AE",
    "0A03AF",
    "0A03B0",
    "0A03B1",
    "0A069A",
)


def parse_hex_bytes(value: str) -> tuple[int, ...]:
    compact = value.replace("0x", "").replace(" ", "").strip()
    if len(compact) % 2 != 0:
        raise ValueError(f"invalid hex byte sequence: {value}")
    return tuple(int(compact[index : index + 2], 16) for index in range(0, len(compact), 2))


def request_id(request: tuple[int, ...]) -> str:
    return "".join(f"{byte:02X}" for byte in request)


def cpp_identifier(prefix: str, request: tuple[int, ...]) -> str:
    return f"{prefix}_{request_id(request).lower()}"


def format_float(value: object) -> str:
    text = str(value)
    if "." not in text:
        text = f"{text}.0"
    return f"{text}f"


def generate(points_json: Path) -> str:
    data = json.loads(points_json.read_text(encoding="utf-8-sig"))

    requests_by_key = {}
    points = []
    for request in data["requests"]:
        request_bytes = parse_hex_bytes(request["request"])
        requests_by_key[request_id(request_bytes)] = (request_bytes, request["label"])
        for point in request["points"]:
            bit = point.get("bit")
            points.append(
                {
                    "key": point["key"],
                    "request": request_bytes,
                    "offset": int(point["offset"]),
                    "size": int(point["size"]),
                    "scale": format_float(point["scale"]),
                    "bit": -1 if bit is None else int(bit),
                }
            )

    requests = [requests_by_key[key] for key in REQUEST_ORDER if key in requests_by_key]

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate_thz55eco_esphome_points.py.",
        "// Source: docs/reference/thz55eco_observed_bulk_points.json",
        "",
        "namespace esphome {",
        "namespace thz55eco {",
        "",
    ]

    for request_bytes, _ in requests:
        values = ", ".join(f"0x{byte:02X}" for byte in request_bytes)
        lines.append(f"static constexpr uint8_t {cpp_identifier('REQUEST', request_bytes)}[] = {{{values}}};")

    lines.extend(
        [
            "",
            "static constexpr BulkRequestDefinition THZ55ECO_BULK_REQUESTS[] = {",
        ]
    )

    for request_bytes, label in requests:
        identifier = cpp_identifier("REQUEST", request_bytes)
        lines.append(f'    {{{identifier}, sizeof({identifier}), "{label}"}},')

    lines.extend(
        [
            "};",
            "",
            "static constexpr PointDefinition THZ55ECO_POINTS[] = {",
        ]
    )

    for point in points:
        identifier = cpp_identifier("REQUEST", point["request"])
        lines.append(
            "    "
            f'{{"{point["key"]}", {identifier}, sizeof({identifier}), '
            f'{point["offset"]}, {point["size"]}, {point["scale"]}, {point["bit"]}}},'
        )

    lines.extend(
        [
            "};",
            "",
            "}  // namespace thz55eco",
            "}  // namespace esphome",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--points-json", type=Path, default=DEFAULT_POINTS_JSON)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.points_json), encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
