"""Generate ESPHome THZ 5.5 Eco point definitions from the observed JSON mapping."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_POINTS_JSON = Path("docs/reference/thz55eco_observed_bulk_points.json")
DEFAULT_OUTPUT = Path("components/thz55eco/thz55eco_points.h")
REQUEST_ORDER = ("FB", "F2", "F4", "F3", "F5", "FC", "16", "E8", "09", "D1")


def hex_byte(value: str) -> int:
    return int(value.replace("0x", "").strip(), 16)


def format_float(value: object) -> str:
    text = str(value)
    if "." not in text:
        text = f"{text}.0"
    return f"{text}f"


def generate(points_json: Path) -> str:
    data = json.loads(points_json.read_text(encoding="utf-8-sig"))

    requests_by_key = {}
    points = []
    for request in data["requests"]:
        request_byte = hex_byte(request["request"])
        requests_by_key[request["request"].upper()] = (request_byte, request["label"])
        for point in request["points"]:
            bit = point.get("bit")
            points.append(
                {
                    "key": point["key"],
                    "request": request_byte,
                    "offset": int(point["offset"]),
                    "size": int(point["size"]),
                    "scale": format_float(point["scale"]),
                    "bit": -1 if bit is None else int(bit),
                }
            )

    requests = [requests_by_key[key] for key in REQUEST_ORDER if key in requests_by_key]

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate_thz55eco_esphome_points.py.",
        "// Source: docs/reference/thz55eco_observed_bulk_points.json",
        "",
        "namespace esphome {",
        "namespace thz55eco {",
        "",
        "static constexpr BulkRequestDefinition THZ55ECO_BULK_REQUESTS[] = {",
    ]

    for request_byte, label in requests:
        lines.append(f'    {{0x{request_byte:02X}, "{label}"}},')

    lines.extend(
        [
            "};",
            "",
            "static constexpr PointDefinition THZ55ECO_POINTS[] = {",
        ]
    )

    for point in points:
        lines.append(
            "    "
            f'{{"{point["key"]}", 0x{point["request"]:02X}, '
            f'{point["offset"]}, {point["size"]}, {point["scale"]}, {point["bit"]}}},'
        )

    lines.extend(
        [
            "};",
            "",
            "}  // namespace thz55eco",
            "}  // namespace esphome",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--points-json", type=Path, default=DEFAULT_POINTS_JSON)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.points_json), encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
